services:
  ui-dashboard:
    build: .
    image: huaweidashboard:latest
    container_name: huawei-ui-dashboard
    restart: unless-stopped
    env_file: .env
    ports:
      - "3001:3001"
    volumes:
      # Volvemos a apuntar a tu carpeta local real en lugar de 'shared-storage'
      - ./storage:/app/storage
    command: ["pnpm", "run", "service:dashboard"]

  inverter-collector:
    build: .
    image: huaweidashboard:latest
    container_name: huawei-inverter-collector
    restart: unless-stopped
    env_file: .env
    depends_on:
      - ui-dashboard
    volumes:
      - ./storage:/app/storage  # Comparte la misma carpeta local real
    command: ["pnpm", "run", "service:inverter"]

  charger-service:
    build: .
    image: huaweidashboard:latest
    container_name: huawei-charger-service
    restart: unless-stopped
    env_file: .env
    depends_on:
      - ui-dashboard
    ports:
      - "9100:9100"
    volumes:
      - ./storage:/app/storage  # Comparte la misma carpeta local real
    command: ["pnpm", "run", "service:charger"]